package api

import (
	"encoding/json"
	"fmt"
	"regexp"
	"sort"
	"strings"
)

const generatedTypesHeader = `// Code generated by scripts/generate-api-types.sh; DO NOT EDIT.
// Source: GET /api/system/api-contract

`

func generatedFrontendAPITypescript(contract openAPIContract) (string, error) {
	names := make([]string, 0, len(contract.Components.Schemas))
	for name := range contract.Components.Schemas {
		names = append(names, name)
	}
	sort.Strings(names)

	var builder strings.Builder
	builder.WriteString(generatedTypesHeader)
	for _, name := range names {
		definition, err := typeScriptTypeDefinition(name, contract.Components.Schemas[name])
		if err != nil {
			return "", err
		}
		builder.WriteString(definition)
	}
	return builder.String(), nil
}

func typeScriptTypeDefinition(name string, schema map[string]any) (string, error) {
	if schemaType(schema) == "object" && schema["properties"] != nil {
		return typeScriptObjectDefinition(name, schema)
	}
	typeText, err := typeScriptType(schema)
	if err != nil {
		return "", fmt.Errorf("%s: %w", name, err)
	}
	return fmt.Sprintf("export type %s = %s;\n", name, typeText), nil
}

func typeScriptObjectDefinition(name string, schema map[string]any) (string, error) {
	properties := schemaPropertiesMap(schema)
	required := schemaRequiredSet(schema)
	names := make([]string, 0, len(properties))
	for name := range properties {
		names = append(names, name)
	}
	sort.Strings(names)

	var builder strings.Builder
	builder.WriteString("export type ")
	builder.WriteString(name)
	builder.WriteString(" = { ")
	for _, propertyName := range names {
		propertySchema, ok := properties[propertyName].(map[string]any)
		if !ok {
			return "", fmt.Errorf("%s.%s schema is not an object", name, propertyName)
		}
		propertyType, err := typeScriptType(propertySchema)
		if err != nil {
			return "", fmt.Errorf("%s.%s: %w", name, propertyName, err)
		}
		builder.WriteString(typeScriptPropertyName(propertyName))
		if !required[propertyName] {
			builder.WriteString("?")
		}
		builder.WriteString(": ")
		builder.WriteString(propertyType)
		builder.WriteString("; ")
	}
	builder.WriteString("};\n")
	return builder.String(), nil
}

func typeScriptType(schema map[string]any) (string, error) {
	if ref, ok := schema["$ref"].(string); ok {
		return schemaNameFromRef(ref)
	}
	if values, ok := stringSlice(schema["enum"]); ok {
		return typeScriptStringUnion(values), nil
	}
	switch schemaType(schema) {
	case "":
		return "unknown", nil
	case "string":
		return "string", nil
	case "integer", "number":
		return "number", nil
	case "boolean":
		return "boolean", nil
	case "array":
		itemSchema, ok := schema["items"].(map[string]any)
		if !ok {
			return "unknown[]", nil
		}
		itemType, err := typeScriptType(itemSchema)
		if err != nil {
			return "", err
		}
		return itemType + "[]", nil
	case "object":
		if additional, ok := schema["additionalProperties"].(map[string]any); ok {
			valueType, err := typeScriptType(additional)
			if err != nil {
				return "", err
			}
			return "Record<string, " + valueType + ">", nil
		}
		if schema["properties"] != nil {
			inline, err := typeScriptInlineObject(schema)
			if err != nil {
				return "", err
			}
			return inline, nil
		}
		return "Record<string, unknown>", nil
	default:
		return "unknown", nil
	}
}

func typeScriptInlineObject(schema map[string]any) (string, error) {
	properties := schemaPropertiesMap(schema)
	required := schemaRequiredSet(schema)
	names := make([]string, 0, len(properties))
	for name := range properties {
		names = append(names, name)
	}
	sort.Strings(names)

	fields := make([]string, 0, len(names))
	for _, name := range names {
		propertySchema, ok := properties[name].(map[string]any)
		if !ok {
			return "", fmt.Errorf("%s schema is not an object", name)
		}
		propertyType, err := typeScriptType(propertySchema)
		if err != nil {
			return "", err
		}
		optional := ""
		if !required[name] {
			optional = "?"
		}
		fields = append(fields, fmt.Sprintf("%s%s: %s", typeScriptPropertyName(name), optional, propertyType))
	}
	return "{ " + strings.Join(fields, "; ") + " }", nil
}

func schemaType(schema map[string]any) string {
	value, _ := schema["type"].(string)
	return value
}

func schemaPropertiesMap(schema map[string]any) map[string]any {
	properties, _ := schema["properties"].(map[string]any)
	return properties
}

func schemaRequiredSet(schema map[string]any) map[string]bool {
	required := map[string]bool{}
	values, _ := stringSlice(schema["required"])
	for _, value := range values {
		required[value] = true
	}
	return required
}

func schemaNameFromRef(ref string) (string, error) {
	const prefix = "#/components/schemas/"
	if !strings.HasPrefix(ref, prefix) {
		return "", fmt.Errorf("unsupported schema ref %q", ref)
	}
	return strings.TrimPrefix(ref, prefix), nil
}

func typeScriptStringUnion(values []string) string {
	if len(values) == 0 {
		return "string"
	}
	parts := make([]string, 0, len(values))
	for _, value := range values {
		encoded, _ := json.Marshal(value)
		parts = append(parts, string(encoded))
	}
	return strings.Join(parts, " | ")
}

func typeScriptPropertyName(name string) string {
	if typeScriptIdentifier.MatchString(name) {
		return name
	}
	encoded, _ := json.Marshal(name)
	return string(encoded)
}

func stringSlice(value any) ([]string, bool) {
	switch typed := value.(type) {
	case []string:
		return append([]string(nil), typed...), true
	case []any:
		result := make([]string, 0, len(typed))
		for _, item := range typed {
			text, ok := item.(string)
			if !ok {
				return nil, false
			}
			result = append(result, text)
		}
		return result, true
	default:
		return nil, false
	}
}

var typeScriptIdentifier = regexp.MustCompile(`^[A-Za-z_$][A-Za-z0-9_$]*$`)
